---
title: "Day4Solution"
author: "Paul Kubat"
date: "12/21/2021"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
myFile <- "https://raw.githubusercontent.com/Pkubat1230/Advent-of-Code-2015/main/Day3/Day3%20Data"

Day3 <- read.csv(myFile,header = FALSE,colClasses = "character")
```

```{r}
#Part 1
df <- data.frame(EW="0", 
                 NS="0")
ns <- 0
ew <- 0
for(i in 1:nchar(Day3[1,1])){
  if(substr(Day3[1,1],i,i) == "<"){
    ew = ew - 1
  }else if(substr(Day3[1,1],i,i) == ">"){
    ew = ew + 1
  }else if(substr(Day3[1,1],i,i) == "^"){
    ns = ns + 1
  }else{
    ns = ns - 1
  }
  df[nrow(df)+1,] = c(ew,ns)
}
nrow(unique(df[c("EW","NS")]))

```



```{r}
#Part 2
Santadf <- data.frame(EW=0,NS=0,stringsAsFactors=FALSE)
RobotSantadf <- data.frame(EW=0,NS=0,stringsAsFactors=FALSE)

for(i in 1:nchar(Day3[1,1])){
ns <- 0
ew <- 0
  if(substr(Day3[1,1],i,i) == "<"){
    ew =  -1
  }else if(substr(Day3[1,1],i,i) == ">"){
    ew = 1
  }else if(substr(Day3[1,1],i,i) == "^"){
    ns = 1
  }else{
    ns = -1
  }
  if(i %% 2 == "1"){
      Santadf[nrow(Santadf)+1,] = c(ew+tail(Santadf$EW,n=1),ns+tail(Santadf$NS,n=1))
  }else{
      RobotSantadf[nrow(RobotSantadf)+1,] = c(ew+tail(RobotSantadf$EW,n=1),ns+tail(RobotSantadf$NS,n=1))
  }
}

combinedHouses <- rbind(Santadf,RobotSantadf)
nrow(unique(combinedHouses[c("EW","NS")]))
```


